{% set name = "pylammpsmpi" %}
{% set version = "0.2.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: 8b09027bb85745e702080b95a7765f586b2becc93f667741836507822797606b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - executorlib
    - mpi4py
    - numpy
    - versioneer
    - toml
    - setuptools
  run:
    - executorlib >=1.1.0,<=1.1.1
    - python >={{ python_min }}
    - mpi4py >=3.1.4,<=4.0.1
    - numpy >=1.23.5,<=1.26.4

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
