{% set name = "pylammpsmpi" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5e03fce312bd7c1c3a50ec6063277ef197c196f53eb9acee65a6adff5124e64

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - pip
    - mpi4py
    - cloudpickle >=2.2.1
    - lammps >=2022.06.23
    - pympipool >=0.5.0
    - pyzmq >=25.1.0

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pylammpsmpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel Lammps Python interface

  description: |
    Parallel Lammps Python interface
  doc_url: https://pylammpsmpi.readthedocs.io/
  dev_url: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
    - srmnitc
