{% set name = "pylammpsmpi" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: ecc98d08204115d52ad067eb547338fc267768a0b6ac8510060d140f8fe92f8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - mpi4py >=3.1.5
    - pympipool >=0.7.2
    - numpy >=1.26.0

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
    - srmnitc
