{% set name = "pylammpsmpi" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f66c589efeea54ff730d56801fd23ebeb457e44fa0897c2e2c3746b78511af7f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - pip
    - mpi4py >=3.1.4
    - lammps >=2022.06.23
    - pympipool >=0.6.0
    - numpy >=1.23.5
    - ase >=3.22.1
    - scipy >=1.10.1

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pylammpsmpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel Lammps Python interface

  description: |
    Parallel Lammps Python interface
  doc_url: https://pylammpsmpi.readthedocs.io/
  dev_url: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
    - srmnitc
