{% set name = "pylammpsmpi" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: 40baa2fdeb4bbc6060a3919b06d9a8e8542930cfe8b4b8cd952fd26fc0479faa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >3.7
    - pip
    - mpi4py
    - pympipool
    - numpy
    - versioneer
    - toml
  run:
    - python >3.7
    - mpi4py >=3.1.4,<=3.1.5
    - pympipool >=0.7.0,<=0.7.9
    - numpy >=1.23.5,<=1.26.2

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
    - srmnitc
