{% set name = "pylammpsmpi" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c9309730543ecbfa286d7d8cb87482663ec154508c01cf76a8e8b5dc6733817

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >2.7
    - pip
    - {{ mpi }}
  run:
    - python >2.7
    - pip
    - mpi4py
    - lammps
    - dask

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pylammpsmpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel Lammps Python interface

  description: |
    Parallel Lammps Python interface
  doc_url: https://pylammpsmpi.readthedocs.io/
  dev_url: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - jan-janssen
    - srmnitc
