{% set name = "pylammpsmpi" %}
{% set version = "0.2.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: 0c7c345d6aa79cee6aecc796265e073d7703e11403ff3915fe0f9b5f2c234359
  patches:
    - structurecheck.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >3.7
    - pip
    - executorlib
    - mpi4py
    - numpy
    - versioneer
    - toml
  run:
    - executorlib ==0.0.1
    - python >3.7
    - mpi4py >=3.1.4,<=3.1.6
    - numpy >=1.23.5,<=1.26.4

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
