{% set name = "pylammpsmpi" %}
{% set version = "0.2.37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: 46e6e3650d3c3c65129bf2a80bbc20453894f5d22d68151fcdaff1a1cd687d4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - executorlib
    - mpi4py
    - numpy
    - versioneer
    - toml
    - setuptools
  run:
    - python >={{ python_min }}
    - mpi4py >=3.1.4,<=4.1.0
    - executorlib >=1.2.0,<=1.6.0
    - numpy >=1.23.5,<=2.3.1

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
