{% set name = "pylammpsmpi" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cf858efdcd5a1e7678d1ea692de2099da2148dc2b49c535bba3cab1a0938ec6

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >2.7
    - pip
    - {{ mpi }}  # [not win]
  run:
    - python >2.7
    - pip
    - mpi4py  # [not win]
    - lammps
    - dask

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pylammpsmpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Parallel Lammps Python interface'

  description: |
    Parallel Lammps Python interface
  doc_url: https://pylammpsmpi.readthedocs.io/
  dev_url: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - jan-janssen
    - srmnitc
