{% set name = "pylammpsmpi" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba4bf14e8ab0155b4c4df795f88091864575c2f6c8bd2c89c266cb8f3760ce11

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >3.7
    - pip
    - {{ mpi }}
  run:
    - python >3.7
    - pip
    - mpi4py
    - lammps >=2022.06.23
    - dask
    - pyzmq >=25.0.0

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pylammpsmpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel Lammps Python interface

  description: |
    Parallel Lammps Python interface
  doc_url: https://pylammpsmpi.readthedocs.io/
  dev_url: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
    - srmnitc
