{% set name = "pylammpsmpi" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: 2e88f4abb1999f0c28c691f003fc6bf71029eabf769cc1d27619bbff3d8004fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - mpi4py >=3.1.4
    - pympipool >=0.7.0
    - numpy >=1.23.5

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
    - srmnitc
