{% set name = "pylammpsmpi" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50140a472797b246734a033f48359ddb1d042dbac50d4b7a4290d526f71974dd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >3.7
    - pip
    - {{ mpi }}
  run:
    - python >3.7
    - pip
    - mpi4py
    - lammps >=2022.06.23
    - dask

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pylammpsmpi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Parallel Lammps Python interface

  description: |
    Parallel Lammps Python interface
  doc_url: https://pylammpsmpi.readthedocs.io/
  dev_url: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
    - srmnitc
