{% set name = "pylammpsmpi" %}
{% set version = "0.2.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pylammpsmpi-{{ version }}.tar.gz
  sha256: 417b6e2d0a8275591819a7ee266e9a276053d1e7d4ff4b401df412a57630e26c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >3.7
    - pip
    - executorlib
    - mpi4py
    - numpy
    - versioneer
    - toml
  run:
    - executorlib ==0.0.5
    - python >3.7
    - mpi4py >=3.1.4,<=4.0.1
    - numpy >=1.23.5,<=1.26.4

test:
  imports:
    - pylammpsmpi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pylammpsmpi
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
