schema_version: 1

context:
  name: pylammpsmpi
  version: "0.3.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylammpsmpi-${{ version }}.tar.gz
  sha256: 1b8044a1137efb3cb217c9e773e407e275ab119424e49bc8fe8160eaf67c90e0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - executorlib
    - mpi4py
    - numpy
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - mpi4py >=3.1.4,<=4.1.0
    - executorlib >=1.2.0,<=1.7.1
    - numpy >=1.23.5,<=2.3.2

tests:
  - python:
      imports:
        - pylammpsmpi
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Parallel Lammps Python interface
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pylammpsmpi

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
